spring:
  application:
    name: task-manager
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.format_sql: true
        hibernate.open-in-view: false
security:
  jwt:
    secret-key: ${SPRING_JWT_SECRET_KEY}
    expiration-time: 3600000
springdoc:
  api-docs:
    path: /api-docs

